### ISSUE TITLE
<img> can bypass sanitisation and push alerts

### ISSUE THREAD

**Issue by rockyrelay** [fac26/week2-database-nkndi#37]
Can run `<img onerror="alert('hello!')">` in input field and bring up retaining alert, and allows empty input form data entry.

<img width="263" alt="image" src="https://user-images.githubusercontent.com/81175151/214636326-daf68d4a-592b-47d0-af04-3b8e93124489.png">

<img width="567" alt="image" src="https://user-images.githubusercontent.com/81175151/214636478-8adb4440-6a89-4e0f-9c89-56cf34b79249.png">

**Comment by Kr33L** [comment]
Oops. We didn't actually have sanitisation implemented yet. Fixed in PR #54 probably.
