### ISSUE TITLE
Css card transition rule 

### ISSUE THREAD

**Issue by GalKJ** [fac26/week2-database-nkndi#42]
![image](https://user-images.githubusercontent.com/99536044/214636798-d2e7b659-e2e5-42cd-9f57-e9521b701067.png)

By adding `transition: 0.5s ease-in-out;` on `.book` rather than `.book:hover` you will get a smooth transition when user hovers and un-hovers.

Gal :)

**Comment by Psydwinder** [comment]
This has been sorted with 0fe5c6d0f06b7d32b6fe54e6f8f46b524047e066
