### ISSUE TITLE
When you hover over a book card the mouse changes

### ISSUE THREAD

**Issue by LauraK0** [fac26/week2-database-nkndi#44]
The mouse changes to a click icon implying that it is clickable. Consider changing mouse hover or make card clickable?

**Comment by DominicSimpson** [comment]
We can do this in CSS by adding a `cursor: no-pointer` command. What do you think, Iman?

**Comment by Psydwinder** [comment]
This has been sorted in 0fe5c6d0f06b7d32b6fe54e6f8f46b524047e066
